### ISSUE TITLE
Unnecessary padding at the bottom of the page

### ISSUE THREAD

**Issue by RJSprod** [Nevysha/a1111-nevysha-comfy-ui#7]
Space is a very very high value thing in stable diffusion webui. I really appreciate this them, but my biggest complaint is the wasted space between the UI and the attributions at the bottom of the page.

Why is this padding so large? Can it be eliminated?

https://user-images.githubusercontent.com/111059656/235929269-50828c89-dc44-4488-9752-b4d85b7dce4d.mp4

No other real issues for the UI, i think the buttons and text can be tighted a bit, to make it more compact, but otherwise this is easily my favorite UI. I actually followed your word in the reddit thread and upgraded to a new branch just to fully utilize (had some TLS issues that are now resolved).

Please remove this padding, or, can you share instructions how to?

Thanks

**Comment by Nevysha** [comment]
Can you please tell me the resolution of your window in the above video ? Please keep in mind that this extension is mean to be used in a nearly full screen window. 

Anyway, this padding should not be that huge and and I'll look into it.

**Comment by Nevysha** [comment]
Fixed in last release
